name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  determine_version:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.set_version.outputs.VERSION }}
    steps:
      - name: Set version
        id: set_version
        shell: bash
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            VERSION_NAME="${{ github.ref_name }}"
          else
            VERSION_NAME="v${{ github.event.inputs.version }}"
          fi
          # Strip "v" prefix for .NET versioning
          echo "VERSION=${VERSION_NAME#v}" >> $GITHUB_OUTPUT

  build-single-file:
    needs: determine_version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rid: linux-x64
            platform: Linux
            artifact_extension: ''
            
          - rid: win-x64
            platform: Windows
            artifact_extension: '.exe'
            
          - rid: osx-x64
            platform: macOS
            artifact_extension: ''
            
          - rid: osx-arm64
            platform: macOS-arm64
            artifact_extension: ''

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Single File
      run: dotnet publish Apify.csproj -c Release -r ${{ matrix.rid }} --self-contained true -p:PublishSingleFile=true -p:Version=${{ needs.determine_version.outputs.VERSION }}
      
    - name: Install zip
      if: runner.os == 'Linux'
      run: sudo apt-get install -y zip
      
    - name: Prepare Release Asset
      run: |
        ASSET_NAME="apify-${{ needs.determine_version.outputs.VERSION }}-${{ matrix.platform }}"
        mkdir -p release-assets/apify
        mv ./bin/Release/net8.0/${{ matrix.rid }}/publish/apify${{ matrix.artifact_extension }} ./release-assets/apify/
        cd release-assets
        zip -r "../${ASSET_NAME}.zip" apify
        cd ..
        mv "${ASSET_NAME}.zip" release-assets/
      shell: bash

    - name: Upload Release Asset
      uses: actions/upload-artifact@v4
      with:
        name: apify-${{ matrix.platform }}
        path: release-assets/apify-${{ needs.determine_version.outputs.VERSION }}-${{ matrix.platform }}.zip
        
  create-release:
    needs: [determine_version, build-single-file]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Download Linux Artifact
      uses: actions/download-artifact@v4
      with:
        name: apify-Linux
        path: ./release-artifacts
        
    - name: Download Windows Artifact
      uses: actions/download-artifact@v4
      with:
        name: apify-Windows
        path: ./release-artifacts
        
    - name: Download macOS Artifact
      uses: actions/download-artifact@v4
      with:
        name: apify-macOS
        path: ./release-artifacts
        
    - name: Download macOS ARM64 Artifact
      uses: actions/download-artifact@v4
      with:
        name: apify-macOS-arm64
        path: ./release-artifacts
    
    - name: List prepared artifacts
      run: ls -laR ./release-artifacts/
      shell: bash
    
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ needs.determine_version.outputs.VERSION }}
        name: Release ${{ needs.determine_version.outputs.VERSION }}
        draft: false
        prerelease: false
        artifacts: "./release-artifacts/**/*.zip"
        artifactContentType: application/octet-stream
        allowUpdates: true
        removeArtifacts: false
        token: ${{ github.token }}
